FROM remote-host

COPY ./conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN yum -y install nginx openssl --enablerepo=nginx
RUN yum -y install yum-utils http://rpms.remirepo.net/enterprise/remi-release-8.rpm
RUN yum -y module reset php
RUN yum -y module enable php:remi-7.2
RUN yum -y install php php-fpm
#RUN yum --enablerepo=ius-archive -y install php71u-fpm php71u-cli php71u-mysqlnd php71u-soap php71u-xml php71u-zip php71u-json php71u-mcrypt php71u-mbstring php71u-zip php71u-gd
RUN yum clean all
RUN mkdir -p /run/php-fpm/
EXPOSE 80 443

VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./bin/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh
